UPLOADCARE-2
doubletapp/uploadcare-android pull request #1
Opened 2023-08-08 13:54 UTC by justkarleone

updated:
target sdk to 33;
jdk to 17;
kotlin to 1.8.20;
gradle plugin, wrapper, version to 8.1.0;
navigation to 2.5.0;
lifecycle to 2.6.1

2023-08-08 15:34 UTC, CheK539 commented on example/build.gradle
> +        buildConfig = true
Are you sure that you should enable this in example module? Because BuildConfig uses only in widget and library modules

2023-08-08 15:34 UTC, CheK539 commented on example/src/main/AndroidManifest.xml
> +        <provider
Can you explain why do you need it?

2023-08-08 15:34 UTC, CheK539 commented on widget/build.gradle
I caught an exception on app's startup with error about using `FLAG_MUTABLE` for `PendingIntent` on Android 12. The only place I found with `PendingIntent` was `FileUploadWorker`, so I think we should update the version of `WorkManager`. I'm not sure that we should do it now, so it's just a notice

2023-08-09 07:33 UTC, justkarleone commented on example/build.gradle
> +        buildConfig = true
I think it's extra and actually it's not used by this module

2023-08-09 07:34 UTC, justkarleone commented on example/src/main/AndroidManifest.xml
> +        <provider
It will cause an exception because WorkManager is already initialized

2023-08-09 07:35 UTC, justkarleone commented on widget/build.gradle
Fixed by raising work library version

2023-08-09 10:04 UTC, onthecrow requested changes

2023-08-09 10:04 UTC, onthecrow commented on example/src/main/java/com/uploadcare/android/example/viewmodels/UploadViewModel.kt
> +        uploader?.uploadAsync(object : UploadFileCallback {
```kotlin
        uploader = FileUploader(
            client,
            fileUri,
            getContext()
        ).store(true)
            .also { fileUploader ->
                fileUploader.uploadAsync(object : UploadFileCallback {
                    override fun onFailure(e: UploadcareApiException) {
                        allowUploadPause.value = false
                        showProgressOrResult(false, e.message ?: "")
                    }

                    override fun onProgressUpdate(
                        bytesWritten: Long,
                        contentLength: Long,
                        progress: Double
                    ) {
                        if (showUploadProgress.value == true) {
                            uploadProgress.value = (progress * 100).roundToInt()
                        }
                    }

                    override fun onSuccess(result: UploadcareFile) {
                        allowUploadPause.value = false
                        showProgressOrResult(false, result.toString())
                    }
                })
            }
```

2023-08-09 10:04 UTC, onthecrow commented on example/src/main/java/com/uploadcare/android/example/viewmodels/UploadViewModel.kt
> +        multipleUploader?.uploadAsync(object : UploadFilesCallback {
The same as above

2023-08-09 10:04 UTC, onthecrow commented on example/src/main/java/com/uploadcare/android/example/viewmodels/UploadViewModel.kt
> +        uploader?.uploadAsync(object : UploadFileCallback {
The same as above

2023-08-09 10:04 UTC, onthecrow commented on example/src/main/java/com/uploadcare/android/example/viewmodels/UploadViewModel.kt
>                      backgroundUploadUUID.value = result.backgroundUploadUUID
**backgroundUploadUUID** is nullable in **UploadcareWidgetResult**, but **backgroundUploadUUID.value** expects non-nullable value

2023-08-09 10:04 UTC, onthecrow commented on gradle/wrapper/gradle-wrapper.properties
> +networkTimeout=10000
Why?

2023-08-09 10:06 UTC, onthecrow commented on example/src/main/java/com/uploadcare/android/example/viewmodels/UploadViewModel.kt
>                      backgroundUploadUUID.value = result.backgroundUploadUUID
We can fix it in another task, but you have to create the task and place todo and task reference here

2023-08-09 10:46 UTC, onthecrow approved these changes

2023-08-09 10:59 UTC, CheK539 approved these changes

2023-08-09 11:02 UTC, merged