UPLOADCARE-6: Replaced AsyncTask to Coroutines
doubletapp/uploadcare-android pull request #4
Opened 2023-08-10 13:25 UTC by CheK539

2023-08-10 13:36 UTC, justkarleone requested changes

2023-08-10 13:36 UTC, justkarleone commented on library/src/main/java/com/uploadcare/android/library/api/FilesQueryBuilder.kt
> +    private val coroutineScope: CoroutineScope = CoroutineScope(Dispatchers.IO + SupervisorJob())
Why do you create your own CoroutineScope instead of providing it?

2023-08-10 14:05 UTC, justkarleone approved these changes

2023-08-15 13:42 UTC, onthecrow approved these changes

2023-08-15 13:42 UTC, onthecrow commented on library/src/main/java/com/uploadcare/android/library/api/FilesQueryBuilder.kt
> +    private val coroutineScope: CoroutineScope = CoroutineScope(Dispatchers.IO + SupervisorJob())
Why don't we just use the MainScope()?

2023-08-15 14:33 UTC, merged